from utils.utils import load_templates
from utils.table_functions import main_get_tables
from utils.table_functions import main_get_tables_void_fix
from utils.table_functions import main_get_from_non_table
from utils.table_functions import get_small_table
